version: "3.8"


networks:
  shared-services:
    external: true


services:
  node_api_1:
    build:
      context: .
      target: dev
    restart: always
    ports:
      - "8000:3000"
    volumes:
      - ".:/application"
    networks:
      - shared-services

